apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ngkkl9wzr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ngkkl9wzr-python 
  name: ngkkl9wzr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ngkkl9wzr-python 
